notifications:
  email: false

sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g gulp-cli @angular/cli
  - npm install
  - cd demo && npm install && cd -

script:
  - gulp test:ci
  - gulp link
  - gulp link:demo
  - npm run build:demo:ci

after_success: gulp coveralls

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: bin/deploy-gh-pages.sh
#    on:
#      branch: master
#      all_branches: true

cache:
  directories:
    - node_modules
